//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealPlanner.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalProfile
    {
        public System.Guid UserId { get; set; }
        public int DoOption { get; set; }
        public int Gender { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public int Age { get; set; }
        public int ActivityLevel { get; set; }
        public Nullable<decimal> FinalWeight { get; set; }
        public Nullable<int> DaysToGo { get; set; }
    
        public virtual User User { get; set; }
    }
}
